### ISSUE TITLE
Container not building

### ISSUE THREAD

**Issue by Stolr** [rh-messaging/activemq-artemis-operator#29]
Hi , 

The container is not building

```
Step 31/36 : COPY --from=build-env /tmp/go/src/github.com/rh-messaging/activemq-artemis-operator/deploy/crds/* /manifests/0.12.0
When using COPY with more than one source file, the destination must be a directory and end with a /
```

**Comment by mkrutov** [comment]
I can not reproduce it right now. Can you please try again?

**Comment by mattlegall** [comment]
Hi,

I am getting the same doing a docker build (docker version: 19.03.5)

docker build -t activemq-artemis-operator:latest -f build/Dockerfile .
Sending build context to Docker daemon  96.89MB
Step 1/35 : FROM registry.access.redhat.com/ubi7/go-toolset:1.11.13-10 AS build-env
 ---> 36d10e36af27
...
Step 28/35 : COPY --from=build-env /tmp/go/src/github.com/rh-messaging/activemq-artemis-operator/deploy/olm-catalog/${BROKER_NAME}-operator/0.13.0/ /manifests/0.13.0
 ---> 0778fef63f62
Step 29/35 : COPY --from=build-env /tmp/go/src/github.com/rh-messaging/activemq-artemis-operator/deploy/crds/* /manifests/0.9.1
When using COPY with more than one source file, the destination must be a directory and end with a /

Adding a / at the end of lines 39 (i.e. /manifests/0.9.1/) and line 40 (i.e. /manifests/0.13.0/) fixes it.

**Comment by brusdev** [comment]
Since AMQ Broker 7.10.0.OPR.1 the Dockerfile doesn't include the manifests copy
