### ISSUE TITLE
AMQ Operator doesn't work on non-openshift Kubernetes anymore

### ISSUE THREAD

**Issue by mattlegall** [rh-messaging/activemq-artemis-operator#34]
Hi,

This is also raised on Red Hat side as https://issues.redhat.com/browse/ENTMQBR-3503.

I am just wondering if the issue is not simply the lack of k8s specific switch in pkg/controller/broker/v2alpha2/activemqartemis/activemqartemis_reconciler.go#L965. Trying to do RouteList{} will clearly throw in k8s; calling Ingress{} instead in a k8s environment could be the answer.

I am currently not able to build/deploy/test a fix but maybe this hint could provide someone with the proper environment a good starting point!

**Comment by brusdev** [comment]
This issue was fixed in AMQ Broker Operator 7.8.0.OPR.1
