### ISSUE TITLE
Cannot enable METRIC_PLUGIN for Prometheus metrics using operator.

### ISSUE THREAD

**Issue by jhoeflaken** [rh-messaging/activemq-artemis-operator#42]
How can we enable Prometheus metrics using the operator? Now I use the operator and then change the stateful set manually by adding AMQ_ENABLE_METRICS_PLUGIN = 'true'. I would like to do this in the custom resource.

Kind regards,

Jacob

**Comment by brusdev** [comment]
ActiveMQArtemis CR include the field `enableMetricsPlugin` to enable the artemis metrics plugin
