### ISSUE TITLE
incorrect version reference

### ISSUE THREAD

**Issue by pwright** [rh-messaging/activemq-artemis-operator#43]
**Describe the bug**
https://github.com/rh-messaging/activemq-artemis-operator/blob/7.9.z/deploy/operator.yaml#L48
says "By default the *_782 values are utilized."

I think this should be 79? or maybe it should avoid mentioning version?

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - Go [e.g. 1.13.4

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by brusdev** [comment]
@pwright good catch, that comment was removed in AMQ Broker Operator 7.10.0.OPR.1
