### ISSUE TITLE
Override Statefulset fields

### ISSUE THREAD

**Issue by caruccio** [rh-messaging/activemq-artemis-operator#45]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to override some fileds of the underlying Statefulset like nodeselector, tolerations, labes ...

**Describe the solution you'd like**

A new field `ActiveMQArtemis.spec.statefulsetOverrides` (or similar) that will apply to underlying Statefulset.

**Describe alternatives you've considered**

Right now I need to yaml-patch the SS in order to run the queue in a specific set of nodes.

**Comment by brusdev** [comment]
@caruccio this is a midstream project, it is mainly used for building purposes. I cloned your issue in the upstream artemiscloud.io project: https://github.com/artemiscloud/activemq-artemis-operator/issues/114
