### ISSUE TITLE
Multiple AMQ Broker pods placed onto the same cluster node

### ISSUE THREAD

**Issue by noseka1** [rh-messaging/activemq-artemis-operator#50]
**Describe the bug**

I think I found an issue that causes the OpenShift/Kubernetes scheduler to place multiple AMQ Broker pods onto a single node. There is a PodTopologySpread plugin used in the OpenShift/Kubernetes scheduler. This plugin ensures that pods that belong to the same Service are spread across hosts and AZs. In our AMQ Broker scenario, this plugin detects that the Broker pods are deployed behind multiple Services. These Services were created by the AMQ Broker operator based on the ActiveMQArtemis CR configuration.

One of the Services looks as follows: 

```
$ oc get svc broker-hdls-svc -o yaml
apiVersion: v1
  kind: Service  metadata:
    name: broker-hdls-svc
    namespace: amq-broker  spec:
  ...
    selector:
      ActiveMQArtemis: broker
      application: broker-app
```

The selector in the above Service matches all three Broker pods. The scheduler would normally spread those pods across hosts/AZs. Unfortunately, the AMQ Broker operator also creates Services like this one:

```
$ oc get svc broker-wconsj-0-svc -o yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: broker-wconsj-0-svc
    namespace: amq-broker
  spec:
    selector:
      ActiveMQArtemis: broker
      application: broker-app
      statefulset.kubernetes.io/pod-name: broker-ss-0
```

The selector in the above Service matches a single Broker pod. This seems to break the logic of the PodTopologySpread plugin. If my understanding is correct, the plugin merges all possible Service selectors and finds the smallest pod groups that belong to the same Service. To those groups, the spread constraint is applied. Unfortunately, in our case, we get three groups with a single Broker pod per group. So, the plugin has no effect on scheduling.

The services like the example above are created by the AMQ Broker operator when any one of these ActiveMQArtemis options is true:

spec.acceptors.expose
spec.console.expose
spec.connectors.expose

If the options are not set, they default to false. So, I removed the above options from the ActiveMQArtemis manifest and since then I can observe the proper spreading of the Broker pods across AZs.

**Platform**
OpenShift 4.9.17
amq-broker-operator.v7.9.3-opr-2

**Comment by brusdev** [comment]
Since AMQ Broker 7.10.0.OPR.1 you can use ActiveMQArtemis.spec.deploymentPlan.affinity to set custom affinity rules.
