### ISSUE TITLE
Operator allows to setup the Jolokia agent, but not the user and password

### ISSUE THREAD

**Issue by arheom** [rh-messaging/activemq-artemis-operator#53]
The operator allows to set up the jolokiaAgentEnabled property, but I could not find a way to set up the user and password for jolokia.

The image allows the following options:
AMQ_ENABLE_JOLOKIA_AGENT
AMQ_JOLOKIA_AGENT_USER
AMQ_JOLOKIA_AGENT_PASSWORD

so, the agent is enabled, but we get a forbidden when trying to access the endpoints.

Any idea if this is an easy change or if we can use a workaround to get the generated user and password?

Thanks!

**Comment by brusdev** [comment]
The only workaround I know is using the custom init image to provide your own broker configuration, see https://artemiscloud.io/blog/initcontainer/

**Comment by brusdev** [comment]
The next release minor (AMQ Broker 7.10.11.OPR.1) will include the field `ActiveMQArtemis.spec.deploymentPlan.env` to set custom environment variables.
